language: ruby
dist: trusty
rvm:
- 2.4.1
branches:
  only:
  - master
scripts:
- bundle exec rake build
before_install:
- eval `ssh-agent -s`
- chmod 600 ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_f8283ae0294e_key -iv $encrypted_f8283ae0294e_iv
  -in deploy_key.enc -out deploy_key -d
- cp deploy_key ~/.ssh/
- chmod 600 ~/.ssh/deploy_key
- ssh-add ~/.ssh/deploy_key
- echo -e "Host skoji.jp\n\tPort 2222\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- build/travis-deploy.sh
notifications:
  email: false
  slack:
    secure: PwOOhuVjSLmLzpuTPRpxxk0rxbph0GCLP27akd7z8QM95bHIOVjcKK/nW1TUeLaU/2yYmhDPPFXW9veLY7JSW35wnZziJJth1OhKMk8IBZsT46kBKl+/KY6euGAVLnbgIO3fP8mh38GGaRXmy/LW1GtITpGrYkVQ3lW5Wx1U6JiC8ThxOBLsFIM1k0JH5MDTmuF4QXIQSePqrI4iMoggtfLbgjTrWgzZ4Y2ZV2YQXVs7ELUJGQ/79c0UVHgo2XiwNKjaxdgJZ8avlNnmrN8xfnd6for7ZU3Ocl9Q7MLD3MnahSnbs+FehFoWzTZ5LuN8v0kG6vr3NFyAeeUzEbHu4KhQdjIFtebgNKbq3+9GHqtGwwb0oHRv8G9ksorkxdwHgrAlCVCiucvNlc/ULzSETJHL/Zkvellkue/DF1GK/R6ndR7L6WSjjXFbQ1hQo7H53O9oD+lm35IIQCYTw+iaUZWLeDzOBOV5WcfGBvEwAm9zJnBKo/DrEjxsO9tzI4/56g/YkVLQkibbWuyJ2aKFYC05LvrEHMVw3+DT36IFq+0npVQi2Kp1k2dLHOBVaPbGPfQViJ/a8amTU87BbWt+ZqCj4+Q1tEebhfqK7s/gt1G4FwlYPxbFRk+WHa2k6XbzTk2XVUblbx3BGigVGVUni5OO5ar9oN1NIjJ+r7pNWvg=
