# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
gems: []
title: 買い物ログ 別館
email: skoji@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Satoshi Kojima. A programmer. Loves cats, beer and MMFR.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://skoji.jp"
twitter_username: skoji
github_username: skoji
permalink: /:year/:month/:title.html
category_slug_map:
    .NET Framework: "net-framework"
    atom: "atom"
    Factor: "factor"
    gepub: "gepub"
    Lisp系: "lisp%e7%b3%bb"
    LowLevel: "lowlevel"
    Lua: "lua"
    R: "r"
    Ruby: "ruby"
    webapp: "webapp"
    イベント: "%e3%82%a4%e3%83%99%e3%83%b3%e3%83%88"
    このブログについて: "%e3%81%93%e3%81%ae%e3%83%96%e3%83%ad%e3%82%b0%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6"
    その他: "%e3%81%9d%e3%81%ae%e4%bb%96"
    ソフトウェア開発: "%e3%82%bd%e3%83%95%e3%83%88%e3%82%a6%e3%82%a7%e3%82%a2%e9%96%8b%e7%99%ba"
    プログラミング言語: "%e3%83%97%e3%83%ad%e3%82%b0%e3%83%a9%e3%83%9f%e3%83%b3%e3%82%b0%e8%a8%80%e8%aa%9e"
    休むに似たり: "%e4%bc%91%e3%82%80%e3%81%ab%e4%bc%bc%e3%81%9f%e3%82%8a"
    未分類: "%e6%9c%aa%e5%88%86%e9%a1%9e"
    本: "%e6%9c%ac"
    開発環境: "%e9%96%8b%e7%99%ba%e7%92%b0%e5%a2%83"
    電子書籍: "%e9%9b%bb%e5%ad%90%e6%9b%b8%e7%b1%8d"
jekyll-archives:
  enabled: [month, categories]
  layouts:
    month: 'month-archive'
    category: 'category-archive'
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'
# Build settings
markdown: kramdown
